[package]
name = "wardstone_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "wardstone"
crate-type = ["cdylib", "staticlib"]

[dependencies]
wardstone_core = { path = "../core" }

[build-dependencies]
cbindgen = "0.25.0"
